name: Android Debug Build

on:
  push:
    branches: [main]
    paths:
      - "package.json"
      - "app.json"
      - "bun.lock"
      - ".github/workflows/dev-build-android.yml"
  pull_request:
    branches: [main]
  workflow_dispatch: {}

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  check-skip:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Skip CI check
        run: echo "Proceeding with workflow"

  build-and-deploy:
    needs: check-skip
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 50
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Get bun cache directory path
        id: bun-cache-dir-path
        run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: 📦 Setup bun cache
        uses: actions/cache@v6
        with:
          path: ${{ steps.bun-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 📦 Install eas-cli dependencies
        run: |
          bun install
          bun add --global eas-cli

      - name: 🔄 Verify EAS CLI installation
        run: |
          echo "EAS CLI version:"
          eas --version

      - name: 📱 Build Development APK
        run: |
          # Build with increased memory limit
          export NODE_OPTIONS="--openssl-legacy-provider --max_old_space_size=4096"
          eas build --platform android --profile staging --local --non-interactive --output=./app-dev.apk
        env:
          NODE_ENV: development

      - name: 📦 Upload build artifacts to GitHub
        uses: actions/upload-artifact@v7
        with:
          name: app-builds
          path: |
            ./app-dev.apk
          retention-days: 7
